### ISSUE TITLE
Admin seeing progress and totals

### ISSUE THREAD

**Issue by heinz-maluti** [heinz-maluti/ELRunning#2]

**Comment by limitlessza** [comment]
What is the goal of this Issue?

**Comment by heinz-maluti** [comment]
Die selfde soos wat die mense die top 10 sien in die view van athelete, moet die admin alles sien.

**Comment by limitlessza** [comment]
@heinz-maluti What is meant with "Everything"?

New screen?
Show the top _n_ people active on the website?
Show all the people on the website?

Maybe see every profile, which events they took part in and how well they did in it?

**Comment by limitlessza** [comment]
Events - Let the admin see the progress of every participant in the admin view.

**Comment by heinz-maluti** [comment]
Added
